2019-03-04 13:47:50,955 globalpy.py[line: 14] INFO: 正在初始化数据库[名称：TESTDB]对象
2019-03-04 13:47:50,967 globalpy.py[line: 17] INFO: 正在获取testlink
2019-03-04 13:47:51,026 main.py[line: 61] INFO: 正在创建测试用例报告报表
2019-03-04 13:47:51,026 mydb.py[line: 37] INFO: query：CREATE TABLE IF NOT EXISTS testcase_report_tb                                         (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,                                          executed_history_id varchar(50) NOT NULL,                                          testcase_id int NOT NULL,                                          testcase_name varchar(40) NOT NULL,                                          testsuit varchar(40),                                          testplan varchar(40),                                          project varchar(40),                                          runresult varchar(20),                                          runtime datetime)
2019-03-04 13:47:51,042 main.py[line: 64] INFO: 正在创建测试步骤报告报表
2019-03-04 13:47:51,042 mydb.py[line: 37] INFO: query：CREATE TABLE IF NOT EXISTS case_step_report_tb                                         (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,                                          executed_history_id varchar(50) NOT NULL,                                          testcase_id int NOT NULL,                                          testcase_name varchar(40) NOT NULL,                                          testplan varchar(40) NOT NULL,                                          project varchar(40) NOT NULL,                                          step_id int,                                          step_num int NOT NULL,                                          step_action varchar(1000),                                           expected_results varchar(1000),                                          runresult varchar(10),                                          reason varchar(2000),                                          protocol_method varchar(40) ,                                          protocol varchar(40),                                          host varchar(40),                                          port int,                                          runtime datetime)
2019-03-04 13:47:51,046 main.py[line: 67] INFO: 正在读取运行模式配置
2019-03-04 13:47:51,047 main.py[line: 72] INFO: 按项目运行测试
2019-03-04 13:47:51,048 main.py[line: 108] INFO: 运行指定项目
2019-03-04 13:47:51,054 main.py[line: 114] ERROR: 测试项目[project：项目1]获取失败，暂时无法执行：problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>
2019-03-04 13:47:51,055 main.py[line: 114] ERROR: 测试项目[project：项目2]获取失败，暂时无法执行：problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>
2019-03-04 13:47:51,056 main.py[line: 114] ERROR: 测试项目[project：项目3]获取失败，暂时无法执行：problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>
2019-03-04 13:47:51,057 main.py[line: 114] ERROR: 测试项目[project：项目4]获取失败，暂时无法执行：problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>
2019-03-04 13:47:51,057 main.py[line: 230] INFO: 接口测试已执行完成，正在关闭数据库连接
2019-03-04 13:47:51,059 htmlreporter.py[line: 38] INFO: 正在查询测试用例总数
2019-03-04 13:47:51,059 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE executed_history_id = %s  data：('20190304134750',)
2019-03-04 13:47:51,060 htmlreporter.py[line: 44] INFO: 正在查询执行通过的用例数
2019-03-04 13:47:51,060 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE runresult = %s AND executed_history_id = %s  data：('Pass', '20190304134750')
2019-03-04 13:47:51,060 htmlreporter.py[line: 50] INFO: 正在查询执行失败的用例数
2019-03-04 13:47:51,061 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE runresult = %s AND executed_history_id = %s  data：('Fail', '20190304134750')
2019-03-04 13:47:51,061 htmlreporter.py[line: 56] INFO: 正在查询执行出错的用例数
2019-03-04 13:47:51,061 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE runresult = %s AND executed_history_id = %s  data：('Error', '20190304134750')
2019-03-04 13:47:51,061 htmlreporter.py[line: 62] INFO: 正在查询未执行的用例数
2019-03-04 13:47:51,062 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE runresult = %s AND executed_history_id = %s  data：('Block', '20190304134750')
2019-03-04 13:47:51,062 htmlreporter.py[line: 73] INFO: 正在查询已运的测试计划
2019-03-04 13:47:51,062 mydb.py[line: 93] INFO: query：SELECT project, testplan FROM testcase_report_tb WHERE executed_history_id = %s GROUP BY project, testplan ORDER BY id ASC  data：('20190304134750',)
2019-03-04 13:47:51,063 htmlreporter.py[line: 116] INFO: 正在查询已运的测试计划
2019-03-04 13:47:51,063 mydb.py[line: 93] INFO: query：SELECT project, testplan FROM testcase_report_tb WHERE executed_history_id = %s GROUP BY project, testplan ORDER BY id ASC  data：('20190304134750',)
2019-03-04 13:47:51,063 htmlreporter.py[line: 178] INFO: 正在设置测试报告结果文件名
2019-03-04 13:47:51,063 htmlreporter.py[line: 188] INFO: 测试报告文件名所在路径为：D:\\interface_project\\report\\test_report20190304134750.html
2019-03-04 13:47:51,063 htmlreporter.py[line: 181] INFO: 正在生成测试报告
2019-03-04 13:47:51,064 main.py[line: 252] INFO: 生成测试报告成功
2019-03-04 13:47:51,424 main.py[line: 259] INFO: D:\\interface_project\\report\\test_report20190304134750.html
2019-03-04 13:47:51,424 main.py[line: 262] INFO: 正在发送测试报告邮件...
2019-03-04 13:54:16,960 globalpy.py[line: 14] INFO: 正在初始化数据库[名称：TESTDB]对象
2019-03-04 13:54:16,969 globalpy.py[line: 17] INFO: 正在获取testlink
2019-03-04 13:54:17,028 main.py[line: 61] INFO: 正在创建测试用例报告报表
2019-03-04 13:54:17,028 mydb.py[line: 37] INFO: query：CREATE TABLE IF NOT EXISTS testcase_report_tb                                         (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,                                          executed_history_id varchar(50) NOT NULL,                                          testcase_id int NOT NULL,                                          testcase_name varchar(40) NOT NULL,                                          testsuit varchar(40),                                          testplan varchar(40),                                          project varchar(40),                                          runresult varchar(20),                                          runtime datetime)
2019-03-04 13:54:17,032 main.py[line: 64] INFO: 正在创建测试步骤报告报表
2019-03-04 13:54:17,032 mydb.py[line: 37] INFO: query：CREATE TABLE IF NOT EXISTS case_step_report_tb                                         (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,                                          executed_history_id varchar(50) NOT NULL,                                          testcase_id int NOT NULL,                                          testcase_name varchar(40) NOT NULL,                                          testplan varchar(40) NOT NULL,                                          project varchar(40) NOT NULL,                                          step_id int,                                          step_num int NOT NULL,                                          step_action varchar(1000),                                           expected_results varchar(1000),                                          runresult varchar(10),                                          reason varchar(2000),                                          protocol_method varchar(40) ,                                          protocol varchar(40),                                          host varchar(40),                                          port int,                                          runtime datetime)
2019-03-04 13:54:17,035 main.py[line: 67] INFO: 正在读取运行模式配置
2019-03-04 13:54:17,036 main.py[line: 72] INFO: 按项目运行测试
2019-03-04 13:54:17,037 main.py[line: 108] INFO: 运行指定项目
2019-03-04 13:54:17,043 main.py[line: 114] ERROR: 测试项目[project：项目1]获取失败，暂时无法执行：problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>
2019-03-04 13:54:17,044 main.py[line: 114] ERROR: 测试项目[project：项目2]获取失败，暂时无法执行：problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>
2019-03-04 13:54:17,045 main.py[line: 114] ERROR: 测试项目[project：项目3]获取失败，暂时无法执行：problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>
2019-03-04 13:54:17,046 main.py[line: 114] ERROR: 测试项目[project：项目4]获取失败，暂时无法执行：problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>
2019-03-04 13:54:17,046 main.py[line: 230] INFO: 接口测试已执行完成，正在关闭数据库连接
2019-03-04 13:54:17,047 htmlreporter.py[line: 38] INFO: 正在查询测试用例总数
2019-03-04 13:54:17,048 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE executed_history_id = %s  data：('20190304135416',)
2019-03-04 13:54:17,048 htmlreporter.py[line: 44] INFO: 正在查询执行通过的用例数
2019-03-04 13:54:17,048 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE runresult = %s AND executed_history_id = %s  data：('Pass', '20190304135416')
2019-03-04 13:54:17,049 htmlreporter.py[line: 50] INFO: 正在查询执行失败的用例数
2019-03-04 13:54:17,049 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE runresult = %s AND executed_history_id = %s  data：('Fail', '20190304135416')
2019-03-04 13:54:17,049 htmlreporter.py[line: 56] INFO: 正在查询执行出错的用例数
2019-03-04 13:54:17,050 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE runresult = %s AND executed_history_id = %s  data：('Error', '20190304135416')
2019-03-04 13:54:17,050 htmlreporter.py[line: 62] INFO: 正在查询未执行的用例数
2019-03-04 13:54:17,050 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE runresult = %s AND executed_history_id = %s  data：('Block', '20190304135416')
2019-03-04 13:54:17,051 htmlreporter.py[line: 73] INFO: 正在查询已运的测试计划
2019-03-04 13:54:17,051 mydb.py[line: 93] INFO: query：SELECT project, testplan FROM testcase_report_tb WHERE executed_history_id = %s GROUP BY project, testplan ORDER BY id ASC  data：('20190304135416',)
2019-03-04 13:54:17,051 htmlreporter.py[line: 116] INFO: 正在查询已运的测试计划
2019-03-04 13:54:17,051 mydb.py[line: 93] INFO: query：SELECT project, testplan FROM testcase_report_tb WHERE executed_history_id = %s GROUP BY project, testplan ORDER BY id ASC  data：('20190304135416',)
2019-03-04 13:54:17,052 htmlreporter.py[line: 178] INFO: 正在设置测试报告结果文件名
2019-03-04 13:54:17,052 htmlreporter.py[line: 188] INFO: 测试报告文件名所在路径为：D:\\interface_project\\report\\test_report20190304135416.html
2019-03-04 13:54:17,052 htmlreporter.py[line: 181] INFO: 正在生成测试报告
2019-03-04 13:54:17,053 main.py[line: 252] INFO: 生成测试报告成功
2019-03-04 13:54:17,303 main.py[line: 259] INFO: D:\\interface_project\\report\\test_report20190304135416.html
2019-03-04 13:54:17,303 main.py[line: 262] INFO: 正在发送测试报告邮件...
2019-03-04 13:56:26,095 globalpy.py[line: 14] INFO: 正在初始化数据库[名称：TESTDB]对象
2019-03-04 13:56:26,102 globalpy.py[line: 17] INFO: 正在获取testlink
2019-03-04 13:56:46,384 globalpy.py[line: 14] INFO: 正在初始化数据库[名称：TESTDB]对象
2019-03-04 13:56:46,392 globalpy.py[line: 17] INFO: 正在获取testlink
2019-03-04 13:57:16,111 globalpy.py[line: 14] INFO: 正在初始化数据库[名称：TESTDB]对象
2019-03-04 13:57:16,118 globalpy.py[line: 17] INFO: 正在获取testlink
2019-03-04 14:03:22,558 globalpy.py[line: 14] INFO: 正在初始化数据库[名称：TESTDB]对象
2019-03-04 14:03:22,566 globalpy.py[line: 17] INFO: 正在获取testlink
2019-03-04 14:03:22,627 main.py[line: 61] INFO: 正在创建测试用例报告报表
2019-03-04 14:03:22,627 mydb.py[line: 37] INFO: query：CREATE TABLE IF NOT EXISTS testcase_report_tb                                         (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,                                          executed_history_id varchar(50) NOT NULL,                                          testcase_id int NOT NULL,                                          testcase_name varchar(40) NOT NULL,                                          testsuit varchar(40),                                          testplan varchar(40),                                          project varchar(40),                                          runresult varchar(20),                                          runtime datetime)
2019-03-04 14:03:22,631 main.py[line: 64] INFO: 正在创建测试步骤报告报表
2019-03-04 14:03:22,631 mydb.py[line: 37] INFO: query：CREATE TABLE IF NOT EXISTS case_step_report_tb                                         (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,                                          executed_history_id varchar(50) NOT NULL,                                          testcase_id int NOT NULL,                                          testcase_name varchar(40) NOT NULL,                                          testplan varchar(40) NOT NULL,                                          project varchar(40) NOT NULL,                                          step_id int,                                          step_num int NOT NULL,                                          step_action varchar(1000),                                           expected_results varchar(1000),                                          runresult varchar(10),                                          reason varchar(2000),                                          protocol_method varchar(40) ,                                          protocol varchar(40),                                          host varchar(40),                                          port int,                                          runtime datetime)
2019-03-04 14:03:22,635 main.py[line: 67] INFO: 正在读取运行模式配置
2019-03-04 14:03:22,636 main.py[line: 72] INFO: 按项目运行测试
2019-03-04 14:03:22,636 main.py[line: 108] INFO: 运行指定项目
2019-03-04 14:03:22,642 main.py[line: 114] ERROR: 测试项目[project：项目1]获取失败，暂时无法执行：problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>
2019-03-04 14:03:22,643 main.py[line: 114] ERROR: 测试项目[project：项目2]获取失败，暂时无法执行：problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>
2019-03-04 14:03:22,644 main.py[line: 114] ERROR: 测试项目[project：项目3]获取失败，暂时无法执行：problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>
2019-03-04 14:03:22,646 main.py[line: 114] ERROR: 测试项目[project：项目4]获取失败，暂时无法执行：problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>
2019-03-04 14:03:22,646 main.py[line: 230] INFO: 接口测试已执行完成，正在关闭数据库连接
2019-03-04 14:03:22,646 htmlreporter.py[line: 38] INFO: 正在查询测试用例总数
2019-03-04 14:03:22,647 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE executed_history_id = %s  data：('20190304140322',)
2019-03-04 14:03:22,647 htmlreporter.py[line: 44] INFO: 正在查询执行通过的用例数
2019-03-04 14:03:22,647 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE runresult = %s AND executed_history_id = %s  data：('Pass', '20190304140322')
2019-03-04 14:03:22,648 htmlreporter.py[line: 50] INFO: 正在查询执行失败的用例数
2019-03-04 14:03:22,648 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE runresult = %s AND executed_history_id = %s  data：('Fail', '20190304140322')
2019-03-04 14:03:22,648 htmlreporter.py[line: 56] INFO: 正在查询执行出错的用例数
2019-03-04 14:03:22,648 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE runresult = %s AND executed_history_id = %s  data：('Error', '20190304140322')
2019-03-04 14:03:22,649 htmlreporter.py[line: 62] INFO: 正在查询未执行的用例数
2019-03-04 14:03:22,649 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE runresult = %s AND executed_history_id = %s  data：('Block', '20190304140322')
2019-03-04 14:03:22,649 htmlreporter.py[line: 73] INFO: 正在查询已运的测试计划
2019-03-04 14:03:22,649 mydb.py[line: 93] INFO: query：SELECT project, testplan FROM testcase_report_tb WHERE executed_history_id = %s GROUP BY project, testplan ORDER BY id ASC  data：('20190304140322',)
2019-03-04 14:03:22,650 htmlreporter.py[line: 116] INFO: 正在查询已运的测试计划
2019-03-04 14:03:22,650 mydb.py[line: 93] INFO: query：SELECT project, testplan FROM testcase_report_tb WHERE executed_history_id = %s GROUP BY project, testplan ORDER BY id ASC  data：('20190304140322',)
2019-03-04 14:03:22,650 htmlreporter.py[line: 178] INFO: 正在设置测试报告结果文件名
2019-03-04 14:03:22,650 htmlreporter.py[line: 188] INFO: 测试报告文件名所在路径为：D:\\interface_project\\report\\test_report20190304140322.html
2019-03-04 14:03:22,650 htmlreporter.py[line: 181] INFO: 正在生成测试报告
2019-03-04 14:03:22,652 main.py[line: 252] INFO: 生成测试报告成功
2019-03-04 14:03:22,960 main.py[line: 259] INFO: D:\\interface_project\\report\\test_report20190304140322.html
2019-03-04 14:03:22,961 main.py[line: 262] INFO: 正在发送测试报告邮件...
2019-03-04 14:09:20,910 globalpy.py[line: 14] INFO: 正在初始化数据库[名称：TESTDB]对象
2019-03-04 14:09:20,917 globalpy.py[line: 17] INFO: 正在获取testlink
2019-03-04 14:09:20,978 main.py[line: 61] INFO: 正在创建测试用例报告报表
2019-03-04 14:09:20,978 mydb.py[line: 37] INFO: query：CREATE TABLE IF NOT EXISTS testcase_report_tb                                         (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,                                          executed_history_id varchar(50) NOT NULL,                                          testcase_id int NOT NULL,                                          testcase_name varchar(40) NOT NULL,                                          testsuit varchar(40),                                          testplan varchar(40),                                          project varchar(40),                                          runresult varchar(20),                                          runtime datetime)
2019-03-04 14:09:20,982 main.py[line: 64] INFO: 正在创建测试步骤报告报表
2019-03-04 14:09:20,982 mydb.py[line: 37] INFO: query：CREATE TABLE IF NOT EXISTS case_step_report_tb                                         (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,                                          executed_history_id varchar(50) NOT NULL,                                          testcase_id int NOT NULL,                                          testcase_name varchar(40) NOT NULL,                                          testplan varchar(40) NOT NULL,                                          project varchar(40) NOT NULL,                                          step_id int,                                          step_num int NOT NULL,                                          step_action varchar(1000),                                           expected_results varchar(1000),                                          runresult varchar(10),                                          reason varchar(2000),                                          protocol_method varchar(40) ,                                          protocol varchar(40),                                          host varchar(40),                                          port int,                                          runtime datetime)
2019-03-04 14:09:20,985 main.py[line: 67] INFO: 正在读取运行模式配置
2019-03-04 14:09:20,987 main.py[line: 72] INFO: 按项目运行测试
2019-03-04 14:09:20,987 main.py[line: 108] INFO: 运行指定项目
2019-03-04 14:09:20,993 main.py[line: 114] ERROR: 测试项目[project：项目1]获取失败，暂时无法执行：problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>
2019-03-04 14:09:20,994 main.py[line: 114] ERROR: 测试项目[project：项目2]获取失败，暂时无法执行：problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>
2019-03-04 14:09:20,995 main.py[line: 114] ERROR: 测试项目[project：项目3]获取失败，暂时无法执行：problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>
2019-03-04 14:09:20,996 main.py[line: 114] ERROR: 测试项目[project：项目4]获取失败，暂时无法执行：problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc.php
<ProtocolError for localhost/testlink/lib/api/xmlrpc.php: 404 Not Found>
2019-03-04 14:09:20,997 main.py[line: 230] INFO: 接口测试已执行完成，正在关闭数据库连接
2019-03-04 14:09:20,998 htmlreporter.py[line: 38] INFO: 正在查询测试用例总数
2019-03-04 14:09:20,998 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE executed_history_id = %s  data：('20190304140920',)
2019-03-04 14:09:20,999 htmlreporter.py[line: 44] INFO: 正在查询执行通过的用例数
2019-03-04 14:09:20,999 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE runresult = %s AND executed_history_id = %s  data：('Pass', '20190304140920')
2019-03-04 14:09:20,999 htmlreporter.py[line: 50] INFO: 正在查询执行失败的用例数
2019-03-04 14:09:20,999 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE runresult = %s AND executed_history_id = %s  data：('Fail', '20190304140920')
2019-03-04 14:09:21,000 htmlreporter.py[line: 56] INFO: 正在查询执行出错的用例数
2019-03-04 14:09:21,000 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE runresult = %s AND executed_history_id = %s  data：('Error', '20190304140920')
2019-03-04 14:09:21,000 htmlreporter.py[line: 62] INFO: 正在查询未执行的用例数
2019-03-04 14:09:21,000 mydb.py[line: 77] INFO: query：SELECT count(testcase_id) FROM testcase_report_tb WHERE runresult = %s AND executed_history_id = %s  data：('Block', '20190304140920')
2019-03-04 14:09:21,001 htmlreporter.py[line: 73] INFO: 正在查询已运的测试计划
2019-03-04 14:09:21,001 mydb.py[line: 93] INFO: query：SELECT project, testplan FROM testcase_report_tb WHERE executed_history_id = %s GROUP BY project, testplan ORDER BY id ASC  data：('20190304140920',)
2019-03-04 14:09:21,001 htmlreporter.py[line: 116] INFO: 正在查询已运的测试计划
2019-03-04 14:09:21,001 mydb.py[line: 93] INFO: query：SELECT project, testplan FROM testcase_report_tb WHERE executed_history_id = %s GROUP BY project, testplan ORDER BY id ASC  data：('20190304140920',)
2019-03-04 14:09:21,002 htmlreporter.py[line: 178] INFO: 正在设置测试报告结果文件名
2019-03-04 14:09:21,002 htmlreporter.py[line: 188] INFO: 测试报告文件名所在路径为：D:\\interface_project\\report\\test_report20190304140920.html
2019-03-04 14:09:21,002 htmlreporter.py[line: 181] INFO: 正在生成测试报告
2019-03-04 14:09:21,003 main.py[line: 252] INFO: 生成测试报告成功
2019-03-04 14:09:21,080 main.py[line: 259] INFO: D:\\interface_project\\report\\test_report20190304140920.html
2019-03-04 14:09:21,080 main.py[line: 262] INFO: 正在发送测试报告邮件...
2019-03-04 14:09:21,616 main.py[line: 266] INFO: 发送邮件成功
2019-03-04 14:18:40,819 globalpy.py[line: 14] INFO: 正在初始化数据库[名称：TESTDB]对象
2019-03-04 14:18:40,826 globalpy.py[line: 17] INFO: 正在获取testlink
